"use client"

import Link from "next/link";
import "../global.css";
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

const navLinks = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "Forgot Password", href: "/forgotPassword" },
];

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gray-50 text-gray-900">
        <div className="gap-4 flex justify-center p-4 shadow-lg">
          {navLinks.map((link) => {
            const isActive = pathName === link.href || (pathName.startsWith(link.href) && link.href !== '/')
            return (
              <Link href={link.href} key={link.name} className={isActive ? "font-bold mr-4":"text-blue-400 mr-4"}>
                {link.name}
              </Link>
            );
          })}
        </div>

        <main className="flex-1 container mx-auto p-6">{children}</main>

        <footer className="bg-gradient-to-r from-slate-700 to-slate-400 text-white p-5 shadow-inner">
          <div className="container mx-auto text-center">
            <p className="text-sm">
              © {new Date().getFullYear()} My Website. All rights reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
