import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gray-50 text-gray-900">
        <header className="bg-gradient-to-r from-red-600 to-red-400 p-5 shadow-lg">
          <div className="container mx-auto flex justify-between items-center ">
            <h1 className="text-xl font-semibold text-white">Header</h1>
          </div>
        </header>
        <main className="flex-1 container mx-auto p-6">{children}</main>

        <footer className="bg-gradient-to-r from-slate-700 to-slate-400 text-white p-5 shadow-inner">
          <div className="container mx-auto text-center">
            <p className="text-sm">
              © {new Date().getFullYear()} My Website. All rights reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
