import '../../global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <div>
        <h1>Featured Products</h1>
        {children}
    </div>
    </>
  )
}
